project:
  type: website

website:
  title: "Andrea's Thoughts"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
#      - icon: twitter
#        href: https://twitter.com
format:
  html:
    theme: vapor
#    mainfont:
    fontcolor: "#49F3FF"
    linkcolor: "#EDBDFF"
    backgroundcolor: "#0118FD"
    
    css: styles.css

editor: visual

